In [146]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math

In [147]:
data = pd.read_csv('train.csv')

In [148]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train  = X_train / 1000


In [149]:
w_1 = np.random.rand(10, 784)
w_2 = np.random.rand(10, 10)
b_1 = np.random.rand(10,1)
dw_1 = np.ones((10, 784))
dw_2 = np.ones((10, 10))
db_1 = np.ones(10)

def relu(x):
    return (x>0) * x
    
def drelu(x):
    return 1 * (x > 0)

def sigmoid(x):
    return 1/(1 + (math.e)**(-x))

def dsigmoid(x):
    return sigmoid(x) * (1-sigmoid(x))

def feedforward(w_1, w_2, b_1, a_0):
    a_1 = np.matmul(w_1, a_0)
    a_1 += b_1.reshape((10,))
    z_1 = a_1
    for i in range(10):
        a_1[i] = sigmoid(a_1[i])
    a_2 = np.matmul(w_2, a_1)
    return z_1,a_1,a_2

def cost(w_1, w_2, b_1, i):
    sum = 0
    temp = np.zeros(10)
    temp[Y_train[i]] = 1
    sum += np.sum((temp - feedforward(w_1, w_2, b_1, X_train[:, i])[2]) ** 2)
    return sum
feedforward(w_1,w_2,b_1,X_train[:,1])

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([4.82197554, 2.45952033, 3.67078538, 4.41125694, 6.30125972,
        5.36992775, 4.57223875, 4.78123206, 4.66151507, 4.5312166 ]))

In [150]:
def epoch(alpha,w_1, w_2, b_1):
    dw_1 = np.ones((10, 784))
    dw_2 = np.ones((10, 10))
    db_1 = np.ones(10) 
    da_2 = np.ones(10)
    da_1 = np.ones(10)
    for i in range(4100):
        z_1,a_1,a_2 = feedforward(w_1,w_2,b_1,X_train[:,i])
        y_2 = np.zeros((1,10)) 
        y_2[0][Y_train[i]] = 1
        da_2 = 2 * (a_2.reshape((1,10))-y_2)
        b_1 = np.matmul(da_2,w_2)
        for x in range(10):
            z_1[x] = dsigmoid(z_1[x])
        b_1 = (1/10)* z_1.reshape(10,1) * b_1.T
        dw_2 = np.matmul(a_1.reshape((10,1)), da_2)
        da_1 = np.matmul(da_2,w_2)
        dw_1 = z_1 * da_1.reshape(10)
        dw_1 = np.matmul(dw_1.reshape((10,1)),X_train[:,i].reshape((1,784)))
        w_1 -= alpha * dw_1
        w_2 -= alpha * dw_2
        b_1 -= alpha * db_1.reshape(10,1)
    return w_1,w_2,b_1
            

In [151]:
1.0000066368942897
for i in range(100):
    w_1, w_2, b_1 = epoch(0.001, w_1, w_2, b_1)
    print(cost(w_1,w_2,b_1,1))
    
cost(w_1,w_2,b_1,1)


9.438724853194701
3.9477819819429767
3.025608857635554
2.729912156192163
2.6025568559022356
1.9585770253511265
1.486113075618835
1.5890145187000486
1.161319876648446
1.1225669071791267
2.2127056261902944
1.1194253471274287
1.0427664173563327
1.116984351939979
1.2885717991611718
3.585771137436376
4.888856894942246
3.9332433051977316
3.1346125887544045
3.2865807633628816
3.4870023895794255
4.010193794167533
3.91050358676548
2.8668576743032603
2.3965527955367394
3.3861289328920616
2.0454399762364193
2.813013723825678
2.046334671030794
1.3739271630925243
1.0143951845909347
1.6073581242595814
1.8764144185195608
1.7320200726033719
1.515449178562066
1.5802877475835668
1.744740608919565
0.8774117647354429
0.973953726578507
1.333808214025777
1.3757111937971662
1.24876207443428
1.1675505104995783
1.1482875792007698
1.1609883115230226
1.210690274431276
1.3604172333133884
1.6469723902258815
1.255622464447582
1.1876592269550894
1.4017173229510744
1.9496735673184573
2.581314695201656
3.1923038648806

0.6032098761234232