In [3]:
#init libraries + data
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math

data = pd.read_csv('train.csv')

data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [81]:
#inits weights and biases + activation functions
w_1 = np.random.rand(10, 784)
w_2 = np.random.rand(10, 10)
b_1 = np.random.rand(10)

def relu(x):
    return (x>0) * x
    
def drelu(x):
    return 1 * (x > 0)

def sigmoid(x):
    return 1/(1 + (math.e)**(-x))

def dsigmoid(x):
    return sigmoid(x) * (1-sigmoid(x))

In [82]:
def feedforward(activation, w, b, a):
  z_out = np.matmul(w,a)
  z_out += b.reshape(10)
  n = z_out.size
  a_out = np.copy(z_out)
  if activation == "sigmoid":
    for i in range(n):
      a_out[i] = sigmoid(z_out[i])
  elif activation == "relu":
    for i in range(n):
      a_out[i] = relu(z_out[i])
  else:
    return "Unrecognized activation function"
  return z_out,a_out
      
def cost(a, i):
    temp = np.zeros(10)
    temp[int(Y_train[i])] = 1
    return (1/10) * np.sum((a-temp)**2)
  

In [88]:
def epoch(alpha,w_1, w_2, b_1):
    dw_1 = np.ones((10, 784))
    dw_2 = np.ones((10, 10))
    db_1 = np.ones(10) 
    da_2 = np.ones(10)
    da_1 = np.ones(10)
    dz_2 = np.ones(10)
    dz_1 = np.ones(10)
    for i in range(10):
        z_1,a_1 = feedforward("sigmoid",w_1,b_1,X_train[:,i])
        z_2,a_2 = feedforward("sigmoid",w_2,np.zeros(10),a_1) 
        
        #solution array
        y_2 = np.zeros(10) 
        y_2[int(Y_train[i])] = 1
        
        #dw_2
        da_2 = (a_2-y_2)
        for x in range(10):
          dz_2[x] = da_2[x] * dsigmoid(z_2[x])
        dw_2 = np.matmul(dz_2.reshape((10,1)),a_1.reshape((1,10)))
        
        #db_1
        da_1 = np.matmul(dz_2.reshape((1,10)),w_2)
        dz_1 = np.copy(da_1)
        for x in range(10):
            dz_1[0][x] = dsigmoid(z_1[x]) * dz_1[0][x]
        db_1 = (1/10)* dz_1.reshape(10)
        
        #dw_1
        dw_1 = np.matmul(dz_1.reshape((10,1)), X_train[:,i].reshape((1,784)))
        
        w_1 -= alpha * dw_1
        w_2 -= alpha * dw_2
        b_1 -= alpha * db_1
    return w_1,w_2,b_1
w_1,w_2,b_1 = epoch(0.1,w_1,w_2,b_1)
print(w_1,w_2,b_1)

[[0.26814817 0.83455311 0.53281267 ... 0.39705447 0.5881216  0.15145791]
 [0.27721713 0.0307702  0.71882925 ... 0.62275648 0.35517416 0.42699517]
 [0.93774778 0.25463127 0.32642489 ... 0.28308045 0.61678989 0.3346939 ]
 ...
 [0.0028664  0.29602516 0.66673032 ... 0.05914159 0.90006719 0.57290709]
 [0.45166227 0.4247493  0.67984787 ... 0.7128884  0.44725353 0.21430107]
 [0.40326125 0.21940817 0.02256348 ... 0.65145057 0.68351034 0.04377266]] [[ 0.97424734  0.98369022  0.18311636  0.7837947   0.2344109   0.85188792
   0.79694844  0.22763742  0.68288833  0.51540403]
 [ 0.43790995  0.17341966  0.43316901  0.35034761  0.51750496  0.22236973
   0.69818753  0.12655977  0.74126136  0.78519303]
 [ 0.54436304  0.68341411  0.42661721  0.41595844  0.33146231  0.63028854
   0.50007602  0.36564914  0.72914527 -0.01641795]
 [ 0.40880663  0.17913649  0.69218806  0.24716178  0.30819082  0.57522452
   0.82373531  0.69132484  0.06728005  0.58980225]
 [ 0.14723205  0.45409897  0.89758294  0.12880769  0.246

In [124]:
#training
for i in range(10):
    w_1, w_2, b_1 = epoch(0.01, w_1, w_2, b_1)
    a_1 = feedforward("sigmoid",w_1,b_1,X_train[:,i])[1]
    a_2 = feedforward("sigmoid",w_2,np.zeros(10),a_1)[1] 
    print(cost(a_2,i))

0.19911703914225434
0.19857097402265705
0.17973655012985745
0.1595571075891102
0.1798266787859004
0.17981470575049086
0.19927340274675864
0.15950039512416042
0.1594861522358196
0.17965379016156258


In [35]:
#accuracy
def accuracy(w_1,w_2,b_1):
    n = 0
    for i in range(41000):
        a_2 = feedforward(w_1,w_2,b_1,X_train[:,i])[3]
        max = 0
        index = 0
        for x in range(10):
            if a_2[x] > max:
                max = a_2[x]
                index = x
        if Y_train[i] == x:
            n += 1
    return n / 41000
print(accuracy(w_1,w_2,b_1))

[[-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]
 [-0.001]]
0.09990243902439025
