In [23]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math

In [24]:
data = pd.read_csv('train.csv')

In [25]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train  = X_train / 1000


In [26]:
w_1 = np.random.rand(10, 784)
w_2 = np.random.rand(10, 10)
b_1 = np.random.rand(10,1)
dw_1 = np.ones((10, 784))
dw_2 = np.ones((10, 10))
db_1 = np.ones(10)

def relu(x):
    return (x>0) * x
    
def drelu(x):
    return 1 * (x > 0)

def sigmoid(x):
    return 1/(1 + (math.e)**(-x))

def dsigmoid(x):
    return sigmoid(x) * (1-sigmoid(x))

def feedforward(w_1, w_2, b_1, a_0):
    a_1 = np.matmul(w_1, a_0)
    a_1 += b_1.reshape((10,))
    z_1 = a_1
    for i in range(10):
        a_1[i] = sigmoid(a_1[i])
    a_2 = np.matmul(w_2, a_1)
    return z_1,a_1,a_2

def cost(w_1, w_2, b_1, i):
    sum = 0
    temp = np.zeros(10)
    temp[Y_train[i]] = 1
    sum += np.sum((temp - feedforward(w_1, w_2, b_1, X_train[:, i])[2]) ** 2)
    return sum
feedforward(w_1,w_2,b_1,X_train[:,1])

(array([0.99999938, 0.9999993 , 0.99999967, 0.99999972, 0.9999996 ,
        0.99999948, 0.99999951, 0.99999816, 0.99999824, 0.99999899]),
 array([0.99999938, 0.9999993 , 0.99999967, 0.99999972, 0.9999996 ,
        0.99999948, 0.99999951, 0.99999816, 0.99999824, 0.99999899]),
 array([4.09668576, 5.80199528, 4.15358202, 3.54419526, 6.1025885 ,
        6.84506311, 4.01230695, 5.19178721, 5.12078156, 5.36104434]))

In [27]:
def epoch(alpha,w_1, w_2, b_1):
    dw_1 = np.ones((10, 784))
    dw_2 = np.ones((10, 10))
    db_1 = np.ones(10) 
    da_2 = np.ones(10)
    da_1 = np.ones(10)
    for i in range(4100):
        z_1,a_1,a_2 = feedforward(w_1,w_2,b_1,X_train[:,i])
        y_2 = np.zeros((1,10)) 
        y_2[0][Y_train[i]] = 1
        da_2 = 2 * (a_2.reshape((1,10))-y_2)
        b_1 = np.matmul(da_2,w_2)
        for x in range(10):
            z_1[x] = dsigmoid(z_1[x])
        b_1 = (1/10)* z_1.reshape(10,1) * b_1.T
        dw_2 = np.matmul(a_1.reshape((10,1)), da_2)
        da_1 = np.matmul(da_2,w_2)
        dw_1 = z_1 * da_1.reshape(10)
        dw_1 = np.matmul(dw_1.reshape((10,1)),X_train[:,i].reshape((1,784)))
        w_1 -= alpha * dw_1
        w_2 -= alpha * dw_2
        b_1 -= alpha * db_1.reshape(10,1)
    return w_1,w_2,b_1
            

In [32]:
1.0000066368942897
for i in range(100):
    w_1, w_2, b_1 = epoch(0.001, w_1, w_2, b_1)
    print(cost(w_1,w_2,b_1,1))
    
cost(w_1,w_2,b_1,1)


29980250.572333723
30329378.568898495
99072197.25227502
167017922.42841905
58929404.74010752
161635631.73362315
33648442.91370006
189167137.64187664
174308022.9429186
70218646.83314463
836054246.6363289
314463487.2676526
187378416.17467067
98786337.63658161
19109671.771341372
10177693.473014874
17452960.180458594
44869478.13919894
403261936.55438954
116701660.73083934
159744503.92594555
165560696.3918868
865623148.6730713
6720729691.736481
300057853.1829355
155591129.47136047
65482562.400910795
312947384.1580131
58741579.08573742
75881669.26760963
60640942.557133555
66844993.917508066
71834303.78420982
105938494.882799
57810915.54686932
86237234.094896
723563042.01666
805384960.3012658
526995744.5454061
501550010.0980365
18453687462.80124
206833064.83140147
375841027.04126567
237778955.93679467
223087491.15464163
267466216.02370906
328427651.8724179
248013776.01730403
123653883.83400813
116195318.0512231
310719619.9019507
79955301.44063804
1335535686.5386548


KeyboardInterrupt: 